
package cn.loan.ws.service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "LoanService", targetNamespace = "http://service.ws.loan.cn/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface LoanService {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<cn.loan.ws.service.LoanInfo>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getLoanInfo", targetNamespace = "http://service.ws.loan.cn/", className = "cn.loan.ws.service.GetLoanInfo")
    @ResponseWrapper(localName = "getLoanInfoResponse", targetNamespace = "http://service.ws.loan.cn/", className = "cn.loan.ws.service.GetLoanInfoResponse")
    @Action(input = "http://service.ws.loan.cn/LoanService/getLoanInfoRequest", output = "http://service.ws.loan.cn/LoanService/getLoanInfoResponse")
    public List<LoanInfo> getLoanInfo(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

}
